spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: @db.url@
    username: @db.user@
    password: @db.pass@
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
